version: "3.8"

name: ncfs

services:
    ncfs:
        image: barbarbar338/ncfs:buildx-latest
        container_name: ncfs
        restart: unless-stopped
        network_mode: host
        environment:
            NGROK_TCP_PORT: <game server port here>
            NGROK_AUTH_TOKEN: <Your NGROK auth token here>
            CLOUDFLARE_AUTH_EMAIL: <Your Cloudflare email here>
            CLOUDFLARE_API_KEY: <Your Cloudflare Global API key here>
            CLOUDFLARE_ZONE_ID: <Your domain's Cloudflare Zone ID here>
            CLOUDFLARE_CNAME_RECORD_NAME: server.example.com
            # If the game supports SRV records, put the prefix here, otherwise leave blank
            CLOUDFLARE_SRV_RECORD_NAME: <SRV record name>
            CLOUDFLARE_SRV_RECORD_PREFIX: <SRV record prefix>
